PhotoContest/PhotoContest.Web/Components/RankViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PhotoContest.Services.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PhotoContest.Web.Components
{
    public class RankViewComponent : ViewComponent
    {
        private readonly IRankService rankService;
        private readonly IUserService userService;

        public RankViewComponent(IRankService rankService, IUserService userService)
        {
            this.rankService = rankService;
            this.userService = userService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            StringBuilder result = new StringBuilder();
            result.Append("");

            var currentUser = this.HttpContext.Session.GetString("junkieUsername");
            if(currentUser != null)
            {
                var user = await this.userService.GetAsync(currentUser);
                var rank = await this.rankService.GetJunkieRankByPointsAsync(user.RankingPoints);
                result.Append(rank);
            }

            var currentOrganaizer = this.HttpContext.Session.GetString("organizerUsername");
            if (currentOrganaizer != null)
            {
                result.Append("Organaizer");
            }

            
            return View(result);
            
        }
    }
}

PhotoContest/PhotoContest.Web/Views/Shared/_Accordion.cshtml
@model List<PhotoContest.Web.Models.ReviewViewModel>


<div class="accordion mt-3 mb-3" id="accordionExample">

    @foreach (var review in Model)
    {
        if (review.Comment != null &&  review.Comment.Length > 0)
        {
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse@(review.ReviewId)" aria-expanded="false"
                            aria-controls="collapse@(review.ReviewId)">
                        Scoore: @review.Score, Reviewer: @(review.ReviewerOrganizer??review.ReviewerUser)
                    </button>
                </h2>
                <div id="collapse@(review.ReviewId)" class="accordion-collapse collapse hide" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        Comment: @review.Comment
                    </div>
                </div>
            </div>
        }
    }

</div>

PhotoContest/PhotoContest.Web/Views/Shared/_ContestCard.cshtml
@model PhotoContest.Services.DTOs.ContestDTO

@{
    var finalDate = Model.CreateOnDate.AddDays(Model.TimeLimitPhaseOne);
}
 
<div class="col-sm-12 col-md-6 col-lg-6 col-xl-3 col-xxl-3">
    <div class="card border-primary mb-3" style="max-width: 18rem;">
        <div class="card-header">@Model.Title</div>
        <div class="card-body text-primary">
            <h5 class="card-title">@Model.ContestType</h5>
            <p class="card-text">Created: @Model.CreateOnDate</p>


            @if (Context.Session.GetString("organizerUsername") != null)
            {
                <a class="btn btn-primary col-6" asp-controller="Dashboard" asp-action="Contest" asp-route-id="@Model.ContestId">Details</a>
            }
            else if (Context.Session.GetString("junkieUsername") != null)
            {
                @if (DateTime.UtcNow > Model.CreateOnDate && finalDate > DateTime.UtcNow && Model.ContestType.ToLower().Equals("open"))
                {
                    <a class="btn btn-primary col-6" asp-controller="Dashboard" asp-action="Contest" asp-route-id="@Model.ContestId">Enroll</a>
                }
                else
                {
                    <a class="btn btn-primary col-6" asp-controller="Dashboard" asp-action="Contest" asp-route-id="@Model.ContestId">Details</a>
                }

            }
            else
            {
                <a class="btn btn-primary col-6" asp-controller="Account" asp-action="Login">Details</a>
            }

        </div>
    </div>
</div>

PhotoContest/PhotoContest.Web/Views/Shared/_ContestCardWhite.cshtml
@model PhotoContest.Services.DTOs.ContestDTO

<div class="col-sm-12 col-md-6 col-lg-6 col-xl-3 col-xxl-3">
    <div class="card border-primary mb-3" style="max-width: 18rem;">
        <div class="card-header">@Model.Title</div>
        <div class="card-body text-primary">
            <h5 class="card-title">@Model.ContestType</h5>
            <p class="card-text">Created: @Model.CreateOnDate</p>
            <a class="btn btn-primary col-6" asp-controller="Dashboard" asp-action="Contest" asp-route-id="@Model.ContestId">Details</a>
        </div>
    </div>
</div>

PhotoContest/PhotoContest.Web/Views/Shared/_ContestItemCard.cshtml
@model PhotoContest.Web.Models.ContestItemViewModel

<div class="col-sm-12 col-md-6 col-lg-6 col-xl-3 col-xxl-3">
    <div class="card">
        <img class="card-img-top" src="~/uploads/@Model.PhotoName" alt="Card image cap">
        <div class="card-body">
            <h4 class="card-title">@Model.Title</h4>
            <p class="card-text">@Model.Story</p>
            @if (Context.Session.GetString("junkieUsername") != null || Context.Session.GetString("organizerUsername") != null)
            {
                <a asp-controller="Dashboard" asp-action="ContestItem" asp-route-id="@Model.ContestItemId" class="btn btn-primary">Details</a>
            }
            else
            {
                <a asp-controller="Account" asp-action="Login" class="btn btn-primary">Details</a>
            }

        </div>
    </div>
</div>

PhotoContest/PhotoContest.Web/Views/Shared/_DashboardLink.cshtml
@if (Context.Session.GetString("junkieUsername") != null)
{
    <li class="nav-item pull-righ">
        <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Junkie">Dashboard</a>
    </li>
}

@if (Context.Session.GetString("organizerUsername") != null)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="CreateContest">Create Contest</a>
    </li>
    <li class="nav-item pull-righ">
        <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Organizer">Dashboard</a>
    </li>
}

PhotoContest/PhotoContest.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Photo Contest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
    @RenderSection("Style", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" width="200" alt="PhotoContests" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Contests">Contests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Photos">Gallery</a>
                        </li>

                        @await Html.PartialAsync("_DashboardLink")
                        @if (Context.Session.GetString("organizerUsername") == null && Context.Session.GetString("junkieUsername") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item pull-righ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }


                    </ul>
                </div>
                <div>
                    @await Component.InvokeAsync("Rank")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PhotoContest.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
    
    @RenderSection("Scripts", required: false)
</body>
</html>

PhotoContest/PhotoContest.Web/Views/Shared/_UserCard.cshtml
@model PhotoContest.Web.Models.UserViewModel

<li class="person" data-chat="person1">
    <div class="user">
        <img src="/images/avatar.png" alt="Retail Admin">
        <span class="status busy"></span>
    </div>
    <p class="name-time">
        <span class="name">@Model.FirsName @Model.LastName</span>
        <span class="time">       </span>
        <span class="time">Username: @Model.Username</span>
        <span class="time">Rating: @Model.RankingPoints</span>
        <span class="time">Rank: @Model.Rank</span>
    </p>
</li>