PhotoContest/PhotoContest.Web/Models/ContestItemViewModel.cs
using System.Collections.Generic;

namespace PhotoContest.Web.Models
{
    public class ContestItemViewModel
    {
        public int ContestItemId { get; set; }
        public string Name { get; set; }
        public int ContestId { get; set; }
        public string Title { get; set; }
        public string Story { get; set; }
        public double Score { get; set; }
        public string PhotoName { get; set; }
        public List<ReviewViewModel> Reviews { get; set; } = new List<ReviewViewModel>();

    }
}

PhotoContest/PhotoContest.Web/Models/ContestViewModel.cs
using PhotoContest.Services.DTOs;
using System.Collections.Generic;

namespace PhotoContest.Web.Models
{
    public class ContestViewModel
    {
        public int ContestId { get; set; }
        public bool IsAbleToEnroll { get; set; }
        public bool IsCurrentUserContestJury { get; set; }
        public string Title { get; set; }
        public string Photo { get; set; }
        public int CurrentUserRaitingPoints { get; set; }
        public string TimeToNextPhase { get; set; }
        public string Category { get; set; }
        public string ContestType { get; set; }
        public string CurrentPhase { get; set; }
        public string TimeUntilNextPhase { get; set; }
        public double Score { get; set; }
        public bool IsEnrolled { get; set; }
        public bool IsInvited { get; set; }
        public List<ContestItemViewModel> ContestItems { get; set; } = new List<ContestItemViewModel>();
        public List<WinnerViewModel> ContestWiners { get; set; } = new List<WinnerViewModel>();
        public PhaseOneViewModel PhaseOneViewModel { get; set; }
        public PhaseTwoViewModel PhaseTwoViewModel { get; set; }
    }
}

PhotoContest/PhotoContest.Web/Models/ContestsViewModel.cs
using PhotoContest.Services.DTOs;
using System.Collections.Generic;

namespace PhotoContest.Web.Models
{
    public class ContestsViewModel
    {
        public List<ContestDTO> Contests { get; set; }
        public string SelectedType { get; set; }
    }
}

PhotoContest/PhotoContest.Web/Models/CreateContestViewModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PhotoContest.Web.Models
{
    public class CreateContestViewModel
    {
        [Required]
        public string Title { get; set; }
        [Required]
        [BindProperty]
        public int Category { get; set; }
        public List<SelectListItem> Categories { get; set; }
        [Required]
        [BindProperty]
        public int Type { get; set; }

        public List<SelectListItem> Types { get; set; }

        [Required]
        [DisplayName("Start Date")]
        public DateTime StartDate { get; set; }

        [BindProperty]
        public List<int> Participants { get; set; }
        public List<SelectListItem> ParticipantsAsSelList { get; set; }

        [DisplayName("Phase One")]
        [Range(1, 31)]
        [Required]
        public int PhaseOne { get; set; }
        [DisplayName("Phase Two")]
        [Range(1, 24)]
        [Required]
        public int PhaseTwo { get; set; }
        [Required]
        [BindProperty]
        public List<int> Juries { get; set; }
        public List<SelectListItem> JuriesAsSelList { get; set; }
        public IFormFile Image { get; set; }
    }
}

PhotoContest/PhotoContest.Web/Models/OrganizerViewModel.cs
namespace PhotoContest.Web.Models
{
    public class OrganizerViewModel
    {
        public string FirsName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
    }
}

PhotoContest/PhotoContest.Web/Models/UserViewModel.cs
namespace PhotoContest.Web.Models
{
    public class UserViewModel
    {
        public int UserId { get; set; }
        public string FirsName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int RankingPoints { get; set; }
        public string Rank { get; set; }
    }
}

PhotoContest/PhotoContest.Web/Components/PhaseOneViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PhotoContest.Services.Contracts;
using PhotoContest.Web.Models;
using System.Threading.Tasks;

namespace PhotoContest.Web.ViewComponents
{
    public class PhaseOneViewComponent : ViewComponent
    {
        private readonly IContestItemService contestItemService;
        private readonly IContestService contestService;

        public PhaseOneViewComponent(IContestItemService contestItemService, IContestService contestService)
        {
            this.contestItemService = contestItemService;
            this.contestService = contestService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int id)
        {
            var model = new PhaseOneViewModel();
            model.ContestId = id;
            return View(model);
        }
    }
}

PhotoContest/PhotoContest.Web/Components/PhaseTwoViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PhotoContest.Services.Contracts;
using PhotoContest.Web.Models;
using System.Threading.Tasks;

namespace PhotoContest.Web.ViewComponents
{
    public class PhaseTwoViewComponent : ViewComponent
    {
        private readonly IReviewService reviewService;
        private readonly IContestItemService contestItemService;

        public PhaseTwoViewComponent(IReviewService reviewService, IContestItemService contestItemService)
        {
            this.reviewService = reviewService;
            this.contestItemService = contestItemService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int contestId, int contestItemId)
        {
            var model = new PhaseTwoViewModel();
            //model.ContestItems = MapperConfig.Mapper.ContestItemsDtoToContestItemsVM(await this.contestItemService.GetAllContestItemsForContestAsync(id));
            model.ContestId = contestId;
            model.ContestItemId = contestItemId;
            
            return View(model);
        }
    }
}

PhotoContest/PhotoContest.Web/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PhotoContest.Services.Contracts;
using PhotoContest.Services.DTOs;
using PhotoContest.Web.Helpers;
using PhotoContest.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static PhotoContest.Web.Helpers.CustomAuthorizationAttribute;

namespace PhotoContest.Web.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IContestService contestService;
        private readonly IUserService userService;
        private readonly IOrganizerService organizerService;
        private readonly ICategoryService categoryService;
        private readonly IContestTypeService contestTypeService;
        private readonly IContestItemService contestItemService;
        private readonly IContestJuryService contestJuryService;
        private readonly IReviewService reviewService;
        private readonly IRankService rankService;

        public DashboardController(IContestService contestService,
            IUserService userService, IOrganizerService organizerService,
            ICategoryService categoryService, IContestTypeService contestTypeService,
            IContestItemService contestItemService, IContestJuryService contestJuryService,
            IReviewService reviewService, IRankService rankService)
        {
            this.contestService = contestService;
            this.userService = userService;
            this.organizerService = organizerService;
            this.categoryService = categoryService;
            this.contestTypeService = contestTypeService;
            this.contestItemService = contestItemService;
            this.contestJuryService = contestJuryService;
            this.reviewService = reviewService;
            this.rankService = rankService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Users()
        {
            try
            {
                var users = await this.userService
                .OrderUsersByRatingAsync();

                var usersVM = new List<UserViewModel>();

                foreach (var item in users)
                {
                    var rank = await this.rankService.GetJunkieRankByPointsAsync(item.RankingPoints);
                    usersVM.Add(MapperConfig.Mapper.UserDtoToUserVM(item, rank));
                }
                return View(usersVM);
            }
            catch (Exception ex)
            {
                return View("Error", new ErrorInfo(ex, "Dashboard", "Users"));
            }
        }

        public async Task<IActionResult> Photos() 
        {
            try
            {
                var photos = await this.contestItemService.GetAllAsync();
                return View(MapperConfig.Mapper.ContestItemsDtoToContestItemsVM(photos));
            }
            catch (Exception ex)
            {
                return View("Error", new ErrorInfo(ex, "Dashboard", "Photos"));
            }
        }


        public async Task<IActionResult> Contests(string type)
        {
            try
            {
                var model = new ContestsViewModel();

                if (string.IsNullOrWhiteSpace(type) || type.ToLower().Equals("phaseone"))
                {
                    model.SelectedType = "phaseOne";
                    model.Contests = await this.contestService.GetContestsByPhaseAsync("Phase I");
                }
                else if (type.ToLower().Equals("phasetwo"))
                {
                    model.SelectedType = "phaseTwo";
                    model.Contests = await this.contestService.GetContestsByPhaseAsync("Phase II");
                }
                else if (type.ToLower().Equals("finished"))
                {
                    model.SelectedType = "finished";
                    model.Contests = await this.contestService.GetContestsByPhaseAsync("Finished");
                }

                return View(model);
            }
            catch (Exception ex)
            {
                return View("Error", new ErrorInfo(ex, "Dashboard", "Contests"));
            }
        }

        [CustomAuthorizeAttribute()]
        public async Task<IActionResult> Organizer()
        {
            try
            {
                var viewModel = new DashboardOrganaizerViewModel();
                viewModel.ContestPhaseOne = (await this.contestService.GetContestsByPhaseAsync("Phase I")).Take(8).ToList();
                viewModel.ContestPhaseTwo = (await this.contestService.GetContestsByPhaseAsync("Phase II")).Take(8).ToList();
                viewModel.ContestPhaseFinished = (await this.contestService.GetContestsByPhaseAsync("Finished")).Take(8).ToList();
                var currentOrganaizerUsername = this.HttpContext.Session.GetString("organizerUsername");
                var organizer = await this.organizerService.GetByUsernameAsync(currentOrganaizerUsername);
                viewModel.Organaizer = MapperConfig.Mapper.OrganizerDtoToOrganizerVM(MapperConfig.Mapper.OrganizerToOrganizerDTO(organizer));

                var usersVM = new List<UserViewModel>();
                var users = (await this.userService.OrderUsersByRatingAsync()).Take(10).ToList();

                foreach (var item in users)
                {
                    var rank = await this.rankService.GetJunkieRankByPointsAsync(item.RankingPoints);
                    usersVM.Add(MapperConfig.Mapper.UserDtoToUserVM(item, rank));
                }

                viewModel.Users = usersVM;

                return View(viewModel);
            }
            catch (Exception ex)
            {
                return View("Error", new ErrorInfo(ex, "Dashboard", "Organizer"));
            }
        }

        [CustomAuthorizeAttribute()]
        public async Task<IActionResult> Junkie()
        {
            try
            {
                var viewModel = new DashboardJunkieViewModel();
                var currentUserUsername = this.HttpContext.Session.GetString("junkieUsername");
                var currentUser = await this.userService.GetAsync(currentUserUsername);

                viewModel.User = new UserDTO(currentUser);
                viewModel.OpenContests = await this.contestService.GetAllOpenContestsAsync();
                viewModel.MyRunningContests = await this.contestService.GetJunkieContestsAsync(currentUser.UserId);
                viewModel.MyFinishedContests = await this.contestService.GetJunkieContestsByPhaseAsync(currentUser.UserId, "Finished");
                viewModel.MyRankingInfo = await this.userService.GetRankingInformationAsync(currentUserUsername);
                viewModel.ContestsInvitedIn = currentUser.InvitedUsers.Select(c => new ContestDTO(c.Contest)).ToList();
                viewModel.ContestsJuryIn = await this.contestService.GetContestsThatIsInJury(currentUser.UserId);

                return View(viewModel);
            }
            catch (Exception ex)
            {
                return View("Error", new ErrorInfo(ex, "Dashboard", "Junkie"));
            }
        }

        [CustomAuthorizeAttribute()]
        [HttpGet]
        public async Task<IActionResult> CreateContest()
        {
            try
            {
                var viewModel = new CreateContestViewModel();

                var listCategories = await this.categoryService.GetAllCategoriesAsync();
                var selectListCategories = new List<SelectListItem>();
                foreach (var item in listCategories)
                {
                    selectListCategories.Add(new SelectListItem(item.CategoryName, item.CategoryId.ToString()));
                }
                viewModel.Categories = selectListCategories;

                var listTypes = await this.contestTypeService.GetAllAsync();
                var selelctedTypes = listTypes.Where(t => t.ContestTypeName.ToLower().Equals("open") || t.ContestTypeName.ToLower().Equals("invitational"));
                var selectListTypes = new List<SelectListItem>();
                foreach (var item in selelctedTypes)
                {
                    var selected = item.ContestTypeName.ToLower().Equals("Open") ? true : false;
                    selectListTypes.Add(new SelectListItem(item.ContestTypeName, item.ContestTypeId.ToString(), selected));
                }
                viewModel.Types = selectListTypes;

                var listJuries = await this.userService.GetUsersThatCanBeJuryAsync();
                var selectListJuries = new List<SelectListItem>();
                foreach (var item in listJuries)
                {
                    selectListJuries.Add(new SelectListItem((item.FirsName + " " + item.LastName), item.UserId.ToString()));
                }
                viewModel.JuriesAsSelList = selectListJuries;

                var listParticipants = await this.userService.GetUsersThatCanBeParticipantsAsync();
                var selectListParticipants = new List<SelectListItem>();
                foreach (var item in listParticipants)
                {
                    selectListParticipants.Add(new SelectListItem((item.FirsName + " " + item.LastName), item.UserId.ToString()));
                }
                viewModel.ParticipantsAsSelList = selectListParticipants;

                return View(viewModel);
            }
            catch (Exception ex)
            {
                return View("Error", new ErrorInfo(ex, "Dashboard", "CreateContest"));
            }
        }

        [CustomAuthorizeAttribute()]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateContest(CreateContestViewModel model)
        {
            try
            {
                var newContestDTO = new ContestDTO();

                var currentOrganizerUsername = this.HttpContext.Session.GetString("organizerUsername");

PhotoContest/PhotoContest.Web/Views/Dashboard/Contest.cshtml
@model PhotoContest.Web.Models.ContestViewModel

@{
    ViewData["Title"] = "Contest";
}

@section Style
{
    <link href="~/css/modalimage.css" rel="stylesheet" />
}

<div id="carouselExampleSlidesOnly" class="carousel slide mb-5" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/uploads/@Model.Photo" height="550" class="d-block w-100" alt="@Model.Title">
        </div>
    </div>
</div>

<div class="container">
    <div class="row mb-4">
        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 col-xxl-6">
            <h4>Category: @Model.Category</h4>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 col-xxl-6">
            <p>@Model.TimeToNextPhase</p>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 col-xxl-6">
            <h3>@Model.Title</h3>
        </div>
    </div>

    @if (Model.CurrentPhase.ToLower().Equals("finished"))
    {
        <div class="row mb-4">
            <div class="col-6">
                <h4>Winners</h4>
                <ul class="list-group">
                    @foreach (var item in Model.ContestWiners)
                    {
                        <li class="list-group-item" aria-current="true">@item.UserName Points: @item.RankingPoints Score @item.Score</li>
                    }
                </ul>


            </div>
        </div>
    }
    

    <div class="contest-items">
        <div class="row mb-3">
            <div class="col-2"><strong>Photo</strong></div>
            <div class="col-2"><strong>Title</strong></div>
            <div class="col-2"><strong>Junkie</strong></div>
            <div class="col-4"><strong>Story</strong></div>
            <div class="col-1"><strong>Score</strong></div>
            <div class="col-1"></div>

        </div>
        <hr />

        @foreach (var item in Model.ContestItems)
        {
            <div class="row">
                <div class="col-2">
                    <a class="btn" asp-controller="Dashboard" asp-action="ContestItem" asp-route-id="@item.ContestItemId">
                        <img width="100" src="~/uploads/@item.PhotoName" />
                    </a>
                </div>
                <div class="col-2">@item.Title</div>
                <div class="col-2">@item.Name</div>
                <div class="col-4">@item.Story</div>

                @if (Model.CurrentPhase.ToLower().Equals("finished"))
                {
                    <div class="col-1">
                        @string.Format("{0:N2}", item.Score)
                    </div>
                }


                <div class="col-1 mb-3">
                    @if (Model.CurrentPhase.ToLower().Equals("phase ii") && (AuthHelper.GetCurrentUserType(Context).ToLower().Equals("organaizer")
                      || Model.IsCurrentUserContestJury))
                    {

                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal-@item.ContestItemId">
                            Add Review
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal-@item.ContestItemId" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Review</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        @await Component.InvokeAsync("PhaseTwo", new { contestId = Model.ContestId, contestItemId = item.ContestItemId })
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>

                @if (Model.CurrentPhase.ToLower().Equals("finished") || AuthHelper.GetCurrentUserType(Context).ToLower().Equals("organaizer"))
                {
                    @await Html.PartialAsync("_Accordion", item.Reviews)
                }

            </div>
        }
    </div>

    @{
        if (Model.CurrentPhase.ToLower().Equals("phase i") && AuthHelper.GetCurrentUserType(Context).ToLower().Equals("user"))
        {
            if (Model.IsEnrolled == false)
            {
                if (!Model.IsCurrentUserContestJury)
                {
                    if (Model.IsInvited || Model.ContestType.ToLower().Equals("open"))
                    {
                        @await Component.InvokeAsync("PhaseOne", new { id = Model.ContestId });
                    }
                    else
                    {
                        <h3>You are Not Invited in this Contest!</h3>
                    }

                }
                else
                {
                    <h3>You are Joury in this Contest!</h3>
                }

            }
            else
            {
                <h3>You are enrolled to the Contest!</h3>
            }


        }
    }

</div>


@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () { 

            $("#is-appropriate").click(function () {
                if ($(this).prop("checked") == true) {
                    $('#review-score').val("0");
                   $('#review-score').prop("disabled", true);
                } else if ($(this).prop("checked") == false) {
                   $('#review-score').prop("disabled", false);
                }
            });
        });
    </script>
}

PhotoContest/PhotoContest.Web/Views/Dashboard/ContestItem.cshtml
@model PhotoContest.Web.Models.ContestItemViewModel
@{
    ViewData["Title"] = "Contest Item";
}

@section Style
{
    <link href="~/css/contestitem.css" rel="stylesheet" />
}

<div class="container">
    <div class="row mb-3">
        <div class="col-1">
            <a class="btn btn-outline-primary " asp-controller="Dashboard" asp-action="Contest" asp-route-id="@Model.ContestId">Back</a>
        </div>
        
    </div>
    <div class="col-xl-8col-md-12">
        <div class="card user-card-full">
            <div class="row m-l-0 m-r-0">
                <div class="col-sm-4 bg-c-lite-green user-profile">
                    <div class="card-block text-center text-white">
                        <div class="m-b-25"> <img src="~/uploads/@Model.PhotoName" width="100%" class="img-radius" alt="User-Profile-Image"> </div>
                        <h4 class="f-w-600">@Model.Title</h4>
                        <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="card-block">

                        <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Information</h6>
                        <div class="row">
                            <div class="col-sm-6">
                                <p class="m-b-10 f-w-600">Score</p>
                                <h6 class="text-muted f-w-400">@Model.Score</h6>
                            </div>
                            <div class="col-sm-6">
                                <p class="m-b-10 f-w-600">Story</p>
                                <h6 class="text-muted f-w-400">@Model.Story</h6>
                            </div>
                            <div class="col-sm-6">
                                <p class="m-b-10 f-w-600">Author</p>
                                <h6 class="text-muted f-w-400">@Model.Name</h6>
                            </div>
                        </div>
                        <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">Reviews</h6>

                        @await Html.PartialAsync("_Accordion", Model.Reviews)

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PhotoContest/PhotoContest.Web/Views/Dashboard/Contests.cshtml
@model PhotoContest.Web.Models.ContestsViewModel

@{
    ViewData["Title"] = "Contest";
}

<div class="container">
    <div class="row mb-4">
        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 col-xxl-6">
            <p>
                <h4>Competitions</h4>
                We made a huge list of international photography awards and competitions to help photographers keep up with all 
                the opportunities to gain exposure that are out there. The list is slightly curated to include awards aimed at 
                professional and semi-professional photographers from all around the world, but there are options for amateurs as 
                well. (We also have a huge list of international photography grants and fellowships and photobook publishers).
            </p>
            <ul>
                <li>NPPA’s Best of Photojournalism Awards (December – January)</li>
                <li>Days Japan International Photography Awards (August – January)</li>
                <li>FotoEvidence Book Award (November – January)</li>
                <li>Istanbul Photo Awards (November – January)</li>
                <li>Pictures of the Year International (November – January)</li>
                <li>World Press Photo Awards (December – January)</li>
                <li>CDS Documentary Essay Prize (Biannual / November – March)</li>
                <li>Freelens Award (November – March)</li>
                <li>Lammarhuber Photography Award (November – March)</li>
                <li>Henri Cartier-Bresson Award (March – April)</li>
                <li>Pictures of the Year Latam (March – April)</li>
            </ul>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 col-xxl-6">
            <p><img src="~/uploads/eagle.jpg" width="100%"/></p>
        </div>
    </div>

    <div class="btn-group" role="group" aria-label="Basic example">

        <a class="btn btn-primary" id="phase-one" href="?type=phaseone" role="button">Phase I</a>
        <a class="btn btn-primary" id="phase-two" href="?type=phasetwo" role="button">Phase II</a>
        <a class="btn btn-primary" id="finished" href="?type=finished" role="button">Finished</a>
    </div>

    <div class="row mt-5 mb-3">
        @foreach (var item in Model.Contests)
        {
            @await Html.PartialAsync("_ContestCard", item)
        }
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            var urlParams = new URLSearchParams(window.location.search);

            console.log(urlParams.get('type'));

            if (urlParams.get('type') === "phaseone") {
                $('#phase-one').css("opacity", "0.8");
            } else if (urlParams.get('type') === "phasetwo") {
                $('#phase-two').css("opacity", "0.8");
            } else if (urlParams.get('type') === "finished") {
                $('#finished').css("opacity", "0.8");
            } else {
                $('#phase-one').css("opacity", "0.8");
            }
        });
    </script>
} 

PhotoContest/PhotoContest.Web/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Dashboard Index";
}

<h1>Test Dashboard Index</h1>

PhotoContest/PhotoContest.Web/Views/Dashboard/Junkie.cshtml
@model PhotoContest.Web.Models.DashboardJunkieViewModel
@{
    ViewData["Title"] = "Dashboard";
}

@section Style{
    <link rel="stylesheet" href="~/css/userlist.css" />
}



<div class="container">

    <!-- Row start -->
    <div class="row gutters mb-3">
        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 col-xxl-6">

            <h1>Welcome @Model.User.FirsName @Model.User.LastName</h1>
            <hr />
            <h5>Info</h5>
            <p>@Model.MyRankingInfo</p>
        </div>
    </div>
    <!-- Row end -->

    <div class="row mb-3">
        <h3 class="display-6">Open Contests</h3>
        <hr />
    </div>

    <div class="row mb-3">
        @if (Model.OpenContests.Count != 0)
        {
            @foreach (var item in Model.OpenContests)
            {
                @await Html.PartialAsync("_ContestCard", item)
            }
        }
        else
        {
            <p>There are no items yet!</p>
        }
    </div>

    <div class="row mb-3">
        <h3 class="display-6">Contest that I am a Jury</h3>
        <hr />
    </div>

    <div class="row mb-3">
        @if (Model.ContestsJuryIn.Count != 0)
        {
            @foreach (var item in Model.ContestsJuryIn)
            {
                @await Html.PartialAsync("_ContestCard", item)
            }
        }
        else
        {
            <p>There are no items yet!</p>
        }
    </div>

    <div class="row mb-3">
        <h3 class="display-6">Invited In Contests</h3>
        <hr />
    </div>

    <div class="row mb-3">
        @if (Model.ContestsInvitedIn.Count != 0)
        {
            @foreach (var item in Model.ContestsInvitedIn)
            {
                @await Html.PartialAsync("_ContestCard", item)
            }
        }
        else
        {
            <p>There are no items yet!</p>
        }
    </div>


    <div class="row mb-3">
        <h3 class="display-6">My Running Contests</h3>
        <hr />
    </div>

    <div class="row mb-3">
        @if (Model.MyRunningContests.Count != 0)
        {
            @foreach (var item in Model.MyRunningContests)
            {
                @await Html.PartialAsync("_ContestCard", item)
            }
        }
        else
        {
            <p>There are no items yet!</p>
        }
    </div>


    <div class="row mb-3">
        <h3 class="display-6">My Finished Contests</h3>
        <hr />
    </div>

    <div class="row mb-3">
        @if (Model.MyFinishedContests.Count != 0)
        {
            @foreach (var item in Model.MyFinishedContests)
            {
                @await Html.PartialAsync("_ContestCard", item)
            }
        }
        else
        {
            <p>There are no items yet!</p>
        }
    </div>


</div>

PhotoContest/PhotoContest.Web/Views/Dashboard/Users.cshtml
@model List<PhotoContest.Web.Models.UserViewModel>

@{
    ViewData["Title"] = "Users";
}

@section Style{
    <link rel="stylesheet" href="~/css/userlist.css" />
}


<div class="container">
    <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 col-xxl-6">
        <div class="card m-0">
            <!-- Row start -->
            <div class="users-container">
                <ul class="users">
                    @foreach (var item in Model)
                    {
                        @await Html.PartialAsync("_UserCard", item)
                    }
                </ul>
            </div>
        </div>
    </div>
</div>